from __future__ import annotations

from . import commands as cmd


def register(sub) -> None:
    p = sub.add_parser("make-template", help="Create an empty generic event CSV template.")
    p.add_argument("--out", default="data/events/events_template.csv")
    p.set_defaults(func=cmd.cmd_make_template)

    p = sub.add_parser("init-demo", help="Generate deterministic synthetic demo prices/events.")
    p.add_argument("--out", default="data/demo")
    p.add_argument("--seed", type=int, default=42)
    p.set_defaults(func=cmd.cmd_init_demo)

    p = sub.add_parser("fetch-prices", help="Fetch daily prices from yfinance into local CSV files.")
    p.add_argument("--tickers", nargs="*", default=[])
    p.add_argument("--events", help="Optional event CSV; fetch all tickers appearing there.")
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--start", required=True)
    p.add_argument("--end", required=True)
    p.add_argument("--out-dir", default="data/prices")
    p.set_defaults(func=cmd.cmd_fetch_prices)

    p = sub.add_parser("run-event-study", help="Compute raw and abnormal returns around events.")
    p.add_argument("--events", required=True)
    p.add_argument("--prices-dir", required=True)
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--horizons", default="1,3,10")
    p.add_argument("--estimation-window", type=int, default=120)
    p.add_argument("--estimation-gap", type=int, default=5)
    p.add_argument("--min-estimation-observations", type=int, default=60)
    p.add_argument("--out", default="artifacts/event_study.csv")
    p.set_defaults(func=cmd.cmd_run_event_study)

    p = sub.add_parser("train", help="Train a baseline chronological-split direction model.")
    p.add_argument("--event-study", required=True)
    p.add_argument("--horizon", type=int, default=1)
    p.add_argument("--out-model", default="artifacts/reaction_direction.joblib")
    p.add_argument("--out-report", default="artifacts/model_report.json")
    p.add_argument("--test-size", type=float, default=0.3)
    p.set_defaults(func=cmd.cmd_train)

    p = sub.add_parser("walk-forward", help="Walk-forward event-by-event direction evaluation.")
    p.add_argument("--event-study", required=True)
    p.add_argument("--horizon", type=int, default=1)
    p.add_argument("--min-train", type=int, default=40)
    p.add_argument("--out-predictions", default="artifacts/walk_forward_predictions.csv")
    p.add_argument("--out-report", default="artifacts/walk_forward_report.json")
    p.set_defaults(func=cmd.cmd_walk_forward)

    p = sub.add_parser("purged-walk-forward", help="Walk-forward direction evaluation with recent overlapping rows purged.")
    p.add_argument("--event-study", required=True)
    p.add_argument("--horizon", type=int, default=1)
    p.add_argument("--min-train", type=int, default=40)
    p.add_argument("--purge-days", type=int, default=None)
    p.add_argument("--out-predictions", default="artifacts/purged_walk_forward_predictions.csv")
    p.add_argument("--out-report", default="artifacts/purged_walk_forward_report.json")
    p.set_defaults(func=cmd.cmd_purged_walk_forward)

    p = sub.add_parser("calibrate", help="Compute probability calibration bins from walk-forward predictions.")
    p.add_argument("--predictions", required=True)
    p.add_argument("--probability-column", default="predicted_positive_probability")
    p.add_argument("--target-column", default="y_true")
    p.add_argument("--bins", type=int, default=10)
    p.add_argument("--out", required=True)
    p.set_defaults(func=cmd.cmd_calibrate)

    p = sub.add_parser("simulate-strategy", help="Apply thresholds, costs, and slippage to event-level predictions.")
    p.add_argument("--predictions", required=True)
    p.add_argument("--horizon", type=int, default=1)
    p.add_argument("--probability-column", default="predicted_positive_probability")
    p.add_argument("--return-column", default=None)
    p.add_argument("--long-threshold", type=float, default=0.60)
    p.add_argument("--short-threshold", type=float, default=None)
    p.add_argument("--allow-short", action="store_true")
    p.add_argument("--cost-bps", type=float, default=0.0)
    p.add_argument("--slippage-bps", type=float, default=0.0)
    p.add_argument("--out-trades", default="artifacts/strategy_trades.csv")
    p.add_argument("--out-report", default="artifacts/strategy_report.json")
    p.set_defaults(func=cmd.cmd_simulate_strategy)

    p = sub.add_parser("null-shuffle", help="Shuffle realized returns to build a simple null distribution for a strategy.")
    p.add_argument("--predictions", required=True)
    p.add_argument("--horizon", type=int, default=1)
    p.add_argument("--n-iter", type=int, default=500)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--probability-column", default="predicted_positive_probability")
    p.add_argument("--return-column", default=None)
    p.add_argument("--long-threshold", type=float, default=0.60)
    p.add_argument("--short-threshold", type=float, default=None)
    p.add_argument("--allow-short", action="store_true")
    p.add_argument("--cost-bps", type=float, default=0.0)
    p.add_argument("--slippage-bps", type=float, default=0.0)
    p.add_argument("--out", default="artifacts/null_shuffle_distribution.csv")
    p.add_argument("--out-report", default="artifacts/null_shuffle_report.json")
    p.set_defaults(func=cmd.cmd_null_shuffle)

    p = sub.add_parser("research-backtest", help="Run purged walk-forward, calibration, strategy simulation, and null shuffle in one harness.")
    p.add_argument("--event-study", required=True)
    p.add_argument("--out-dir", default="artifacts/research_backtest")
    p.add_argument("--horizon", type=int, default=1)
    p.add_argument("--min-train", type=int, default=40)
    p.add_argument("--purge-days", type=int, default=None)
    p.add_argument("--probability-threshold", type=float, default=0.60)
    p.add_argument("--allow-short", action="store_true")
    p.add_argument("--cost-bps", type=float, default=0.0)
    p.add_argument("--slippage-bps", type=float, default=0.0)
    p.add_argument("--calibration-bins", type=int, default=10)
    p.add_argument("--null-iterations", type=int, default=500)
    p.add_argument("--seed", type=int, default=42)
    p.set_defaults(func=cmd.cmd_research_backtest)

    p = sub.add_parser("make-placebo-events", help="Create random/shifted non-event placebo controls from an event CSV.")
    p.add_argument("--events", required=True)
    p.add_argument("--prices-dir", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--n-per-event", type=int, default=1)
    p.add_argument("--mode", default="random", choices=["random", "shift"])
    p.add_argument("--shift-days", default="30,60,90,-30,-60,-90")
    p.add_argument("--avoid-window-days", type=int, default=10)
    p.add_argument("--seed", type=int, default=42)
    p.set_defaults(func=cmd.cmd_make_placebo_events)

    p = sub.add_parser("make-peer-controls", help="Create peer-control events by replacing the affected ticker with a peer.")
    p.add_argument("--events", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--peer-map", default=None, help="Optional CSV with ticker,peer_ticker columns.")
    p.add_argument("--universe", default=None, help="Optional CSV with a ticker column; peers rotate through this list.")
    p.set_defaults(func=cmd.cmd_make_peer_controls)

    p = sub.add_parser("predict", help="Run a trained direction model on event-study rows.")
    p.add_argument("--model", required=True)
    p.add_argument("--event-study", required=True)
    p.add_argument("--out")
    p.add_argument("--head", type=int, default=10)
    p.set_defaults(func=cmd.cmd_predict)

    p = sub.add_parser("analogs", help="Find nearest historical analog events by pre-event/event metadata.")
    p.add_argument("--event-study", required=True)
    p.add_argument("--event-id", required=True)
    p.add_argument("--k", type=int, default=5)
    p.add_argument("--horizon", type=int, default=1)
    p.add_argument("--out")
    p.set_defaults(func=cmd.cmd_analogs)

    p = sub.add_parser("report", help="Create a Markdown event-study summary report.")
    p.add_argument("--event-study", required=True)
    p.add_argument("--out", default="artifacts/report.md")
    p.add_argument("--horizon", type=int, default=1)
    p.set_defaults(func=cmd.cmd_report)
