from __future__ import annotations

from . import commands as cmd


def register(sub) -> None:
    p = sub.add_parser("cyber-8k-template", help="Write a Cyber 8-K Watch pipeline config template.")
    p.add_argument("--out", default="cyber_8k_pipeline.json")
    p.add_argument("--source-documents-csv", default="examples/cyber_8k_watch/source_documents.csv")
    p.add_argument("--out-dir", default="artifacts/cyber_8k_watch")
    p.add_argument("--tickers", nargs="*", default=[])
    p.add_argument("--start")
    p.add_argument("--end")
    p.set_defaults(func=cmd.cmd_cyber_8k_template)

    p = sub.add_parser("cyber-8k-source-docs", help="Build Cyber 8-K Watch source-document candidates from SEC filings.")
    p.add_argument("--tickers", nargs="+", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--docs-dir", required=True)
    p.add_argument("--start")
    p.add_argument("--end")
    p.add_argument("--limit-per-ticker", type=int, default=None)
    p.add_argument("--no-primary", action="store_true")
    p.add_argument("--no-exhibits", action="store_true")
    p.add_argument("--overwrite", action="store_true")
    p.add_argument("--min-text-chars", type=int, default=80)
    p.add_argument("--user-agent")
    p.add_argument("--requests-per-second", type=float, default=5.0)
    p.set_defaults(func=cmd.cmd_cyber_8k_source_docs)

    p = sub.add_parser("cyber-8k-parse", help="Parse a Cyber 8-K source-document manifest into claims and evidence spans.")
    p.add_argument("--documents", required=True)
    p.add_argument("--claims-out", required=True)
    p.add_argument("--evidence-out", required=True)
    p.set_defaults(func=cmd.cmd_cyber_8k_parse)

    p = sub.add_parser("cyber-8k-review-queue", help="Build a Cyber 8-K claim/evidence review queue.")
    p.add_argument("--claims", required=True)
    p.add_argument("--evidence-spans", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--auto-accept-min-confidence", type=float, default=None)
    p.add_argument("--allow-missing-evidence", action="store_true")
    p.set_defaults(func=cmd.cmd_cyber_8k_review_queue)

    p = sub.add_parser("cyber-8k-build-dataset", help="Build Cyber 8-K Watch dataset artifacts.")
    p.add_argument("--documents", required=True)
    p.add_argument("--out-dir", required=True)
    p.add_argument("--claims")
    p.add_argument("--evidence-spans")
    p.add_argument("--review-queue")
    p.add_argument("--filings")
    p.add_argument("--run-manifest")
    p.add_argument("--auto-accept-min-confidence", type=float, default=None)
    p.set_defaults(func=cmd.cmd_cyber_8k_build_dataset)

    p = sub.add_parser("cyber-8k-build-site", help="Build a static Cyber 8-K Watch site from dataset CSVs.")
    p.add_argument("--events", required=True)
    p.add_argument("--claims", required=True)
    p.add_argument("--evidence-spans", required=True)
    p.add_argument("--out-dir", required=True)
    p.add_argument("--title", default="Cyber 8-K Watch")
    p.add_argument("--source-documents")
    p.add_argument("--source-docs-dir")
    p.add_argument("--review-queue")
    p.set_defaults(func=cmd.cmd_cyber_8k_build_site)

    p = sub.add_parser("cyber-8k-digest", help="Build a Markdown Cyber 8-K Watch digest.")
    p.add_argument("--events", required=True)
    p.add_argument("--claims", required=True)
    p.add_argument("--evidence-spans", required=True)
    p.add_argument("--start-date")
    p.add_argument("--end-date")
    p.add_argument("--out")
    p.add_argument("--title", default="Cyber 8-K Watch Digest")
    p.set_defaults(func=cmd.cmd_cyber_8k_digest)

    p = sub.add_parser("cyber-8k-quality-report", help="Build a Cyber 8-K Watch dataset quality report.")
    p.add_argument("--events", required=True)
    p.add_argument("--claims", required=True)
    p.add_argument("--evidence-spans", required=True)
    p.add_argument("--review-queue")
    p.add_argument("--out-json")
    p.add_argument("--out-md")
    p.set_defaults(func=cmd.cmd_cyber_8k_quality_report)

    p = sub.add_parser("cyber-8k-run", help="Run the dedicated Cyber 8-K Watch pipeline.")
    p.add_argument("--config", required=True)
    p.add_argument("--dry-run", action="store_true")
    p.set_defaults(func=cmd.cmd_cyber_8k_run)
