from __future__ import annotations

from . import commands as cmd


def register(sub) -> None:
    p = sub.add_parser("biotech-catalyst-source-docs", help="Create FDA/clinical biotech catalyst source-document candidates from SEC 8-Ks and local source manifests.")
    p.add_argument("--preset", default=None)
    p.add_argument("--tickers", nargs="*", default=[])
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--sector-benchmark", default="")
    p.add_argument("--forms", default="8-K")
    p.add_argument("--item-filter", default="7.01,8.01", help="8-K item filter for clinical/FDA current reports.")
    p.add_argument("--start", default=None)
    p.add_argument("--end", default=None)
    p.add_argument("--limit-per-ticker", type=int, default=None)
    p.add_argument("--docs-dir", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--source-manifests", nargs="*", default=[], help="Existing source-document manifests to append, e.g. FDA, ClinicalTrials.gov, or company press-release rows.")
    p.add_argument("--no-sec", action="store_true", help="Skip SEC discovery and only combine supplied source manifests.")
    p.add_argument("--user-agent", default=None)
    p.add_argument("--requests-per-second", type=float, default=5.0)
    p.add_argument("--overwrite", action="store_true")
    p.add_argument("--min-text-chars", type=int, default=40)
    p.set_defaults(func=cmd.cmd_biotech_catalyst_source_docs)

    p = sub.add_parser("parse-biotech-catalysts", help="Parse FDA/clinical biotech source documents into facts, features, and a review queue.")
    p.add_argument("--documents", required=True, help="Source-document manifest.")
    p.add_argument("--facts-out", required=True)
    p.add_argument("--features-out", required=True)
    p.add_argument("--events-out", required=True)
    p.add_argument("--min-confidence", type=float, default=0.0)
    p.add_argument("--usable-confidence", type=float, default=0.70)
    p.set_defaults(func=cmd.cmd_parse_biotech_catalysts)

    p = sub.add_parser("validate-biotech-catalyst-parser", help="Validate biotech catalyst parser facts against a reviewed gold-set CSV.")
    p.add_argument("--facts", required=True)
    p.add_argument("--gold", required=True)
    p.add_argument("--errors-out", required=True)
    p.add_argument("--report-out", required=True)
    p.add_argument("--build-gold-template", action="store_true", help="Create a 60-row parser-proposed gold template from facts; human review is still required.")
    p.set_defaults(func=cmd.cmd_validate_biotech_catalyst_parser)

    p = sub.add_parser("biotech-catalyst-readiness-report", help="Summarize whether a reviewed/enriched biotech catalyst corpus is ready for modeling.")
    p.add_argument("--events", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--min-train", type=int, default=40)
    p.add_argument("--source-documents", default=None)
    p.add_argument("--parser-errors", default=None, help="Optional parser validation errors CSV; if supplied, parser audit must pass.")
    p.set_defaults(func=cmd.cmd_biotech_catalyst_readiness_report)

    p = sub.add_parser("biotech-catalyst-falsification-pass", help="Run the first biotech catalyst event-study and falsification pass.")
    p.add_argument("--events", default="data/events/biotech_catalyst_review_queue.csv")
    p.add_argument("--features", default="data/events/biotech_catalyst_features.csv")
    p.add_argument("--prices-dir", default="data/prices/biotech_catalysts")
    p.add_argument("--out-dir", default="artifacts")
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--sector-benchmark", default="XBI")
    p.add_argument("--horizons", default="1,3,10")
    p.add_argument("--min-train", type=int, default=40)
    p.add_argument("--purge-days", type=int, default=3)
    p.add_argument("--probability-threshold", type=float, default=0.60)
    p.add_argument("--cost-bps", type=float, default=5.0)
    p.add_argument("--slippage-bps", type=float, default=5.0)
    p.add_argument("--null-iterations", type=int, default=500)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--estimation-window", type=int, default=120)
    p.add_argument("--estimation-gap", type=int, default=5)
    p.add_argument("--min-estimation-observations", type=int, default=60)
    p.set_defaults(func=cmd.cmd_biotech_catalyst_falsification_pass)

    p = sub.add_parser("biotech-negative-catalyst-confirmation", help="Run Agent 3G negative binary biotech catalyst narrow confirmation.")
    p.add_argument("--original-event-study", default="artifacts/biotech_catalyst_event_study.csv")
    p.add_argument("--fresh-event-study", default="artifacts/biotech_catalyst_fresh_event_study.csv")
    p.add_argument("--original-source-documents", default="data/events/biotech_catalyst_source_documents.csv")
    p.add_argument("--fresh-source-documents", default="data/events/biotech_catalyst_fresh_source_documents.csv")
    p.add_argument("--prices-dir", default="data/prices/biotech_catalysts")
    p.add_argument("--out-dir", default="artifacts")
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--horizons", default="1,3,10")
    p.add_argument("--seed", type=int, default=777)
    p.add_argument("--estimation-window", type=int, default=120)
    p.add_argument("--estimation-gap", type=int, default=5)
    p.add_argument("--min-estimation-observations", type=int, default=60)
    p.set_defaults(func=cmd.cmd_biotech_negative_catalyst_confirmation)

    p = sub.add_parser("biotech-negative-catalyst-timestamp-repair", help="Run Agent 3I timestamp repair for negative binary biotech catalysts.")
    p.add_argument("--original-event-study", default="artifacts/biotech_catalyst_event_study.csv")
    p.add_argument("--fresh-event-study", default="artifacts/biotech_catalyst_fresh_event_study.csv")
    p.add_argument("--original-source-documents", default="data/events/biotech_catalyst_source_documents.csv")
    p.add_argument("--fresh-source-documents", default="data/events/biotech_catalyst_fresh_source_documents.csv")
    p.add_argument("--prices-dir", default="data/prices/biotech_catalysts")
    p.add_argument("--out-dir", default="artifacts")
    p.add_argument("--sector-benchmark", default="XBI")
    p.add_argument("--horizons", default="1,3,10")
    p.add_argument("--min-train", type=int, default=40)
    p.set_defaults(func=cmd.cmd_biotech_negative_catalyst_timestamp_repair)

    p = sub.add_parser("biotech-negative-catalyst-corrected-confirmation", help="Run Agent 3J corrected timestamp-safe negative biotech catalyst confirmation.")
    p.add_argument("--repaired-events", default="artifacts/biotech_negative_catalyst_timestamp_repaired_events.csv")
    p.add_argument("--timestamp-audit", default="artifacts/biotech_negative_catalyst_timestamp_audit.csv")
    p.add_argument("--duplicate-audit", default="artifacts/biotech_negative_catalyst_duplicate_audit.csv")
    p.add_argument("--prices-dir", default="data/prices/biotech_catalysts")
    p.add_argument("--out-dir", default="artifacts")
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--sector-benchmark", default="XBI")
    p.add_argument("--horizons", default="1,3,10")
    p.add_argument("--seed", type=int, default=779)
    p.add_argument("--estimation-window", type=int, default=120)
    p.add_argument("--estimation-gap", type=int, default=5)
    p.add_argument("--min-estimation-observations", type=int, default=60)
    p.set_defaults(func=cmd.cmd_biotech_negative_catalyst_corrected_confirmation)

    p = sub.add_parser("government-contract-falsification-pass", help="Run the first government-contract event-study and falsification pass.")
    p.add_argument("--events", default="data/events/government_contract_public_eligible_corpus.csv")
    p.add_argument("--prices-dir", default="data/prices/government_contracts")
    p.add_argument("--out-dir", default="artifacts")
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--horizons", default="1,3,10")
    p.add_argument("--min-train", type=int, default=40)
    p.add_argument("--purge-days", type=int, default=10)
    p.add_argument("--probability-threshold", type=float, default=0.60)
    p.add_argument("--cost-bps", type=float, default=5.0)
    p.add_argument("--slippage-bps", type=float, default=5.0)
    p.add_argument("--null-iterations", type=int, default=500)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--estimation-window", type=int, default=120)
    p.add_argument("--estimation-gap", type=int, default=5)
    p.add_argument("--min-estimation-observations", type=int, default=60)
    p.set_defaults(func=cmd.cmd_government_contract_falsification_pass)

    p = sub.add_parser("parse-capital-raises", help="Parse capital raise, dilution, ATM, convertible, and liquidity source documents into reviewable fact/event rows.")
    p.add_argument("--documents", required=True, help="Source-document manifest.")
    p.add_argument("--facts-out", required=True)
    p.add_argument("--features-out", required=True)
    p.add_argument("--events-out", required=True)
    p.add_argument("--min-confidence", type=float, default=0.0)
    p.add_argument("--usable-confidence", type=float, default=0.70)
    p.set_defaults(func=cmd.cmd_parse_capital_raises)

    p = sub.add_parser("capital-raise-sec-source-docs", help="Download SEC financing/dilution source-document candidates.")
    p.add_argument("--preset", default=None)
    p.add_argument("--tickers", nargs="*", default=[])
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--sector-benchmark", default="")
    p.add_argument("--forms", default="8-K,S-1,S-3,424B2,424B3,424B4,424B5,424B7")
    p.add_argument("--item-filter", default="1.01,2.03,3.02,8.01", help="8-K item filter for financing-relevant current reports.")
    p.add_argument("--start", default=None)
    p.add_argument("--end", default=None)
    p.add_argument("--limit-per-ticker", type=int, default=None)
    p.add_argument("--docs-dir", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--user-agent", default=None)
    p.add_argument("--requests-per-second", type=float, default=5.0)
    p.add_argument("--overwrite", action="store_true")
    p.add_argument("--min-text-chars", type=int, default=40)
    p.set_defaults(func=cmd.cmd_capital_raise_sec_source_docs)

    p = sub.add_parser("validate-capital-raise-parser", help="Validate capital-raise parser facts against a reviewed gold-set CSV.")
    p.add_argument("--facts", required=True)
    p.add_argument("--gold", required=True)
    p.add_argument("--errors-out", required=True)
    p.add_argument("--report-out", required=True)
    p.set_defaults(func=cmd.cmd_validate_capital_raise_parser)

    p = sub.add_parser("capital-raise-shares-context", help="Build point-in-time SEC share-count context for capital-raise events.")
    p.add_argument("--events", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--user-agent", default=None)
    p.add_argument("--requests-per-second", type=float, default=5.0)
    p.set_defaults(func=cmd.cmd_capital_raise_shares_context)

    p = sub.add_parser("enrich-capital-raise-context", help="Add discount, dilution, market-cap, and pre-event run-up context to reviewed capital-raise events.")
    p.add_argument("--events", required=True)
    p.add_argument("--prices-dir", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--market-caps", default=None, help="Optional CSV with event_id or ticker/asof_date market_cap_before_event.")
    p.add_argument("--shares-outstanding", default=None, help="Optional CSV with event_id or ticker/asof_date shares_outstanding_before_event.")
    p.set_defaults(func=cmd.cmd_enrich_capital_raise_context)

    p = sub.add_parser("capital-raise-readiness-report", help="Summarize whether a reviewed/enriched capital-raise corpus is ready for modeling.")
    p.add_argument("--events", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--min-train", type=int, default=40)
    p.add_argument("--parser-errors", default=None, help="Optional parser validation errors CSV; if supplied, parser audit must pass.")
    p.set_defaults(func=cmd.cmd_capital_raise_readiness_report)

    p = sub.add_parser("government-contract-source-docs", help="Build government-contract award source-document candidates from USAspending and/or source manifests.")
    p.add_argument("--out", default="data/events/government_contract_source_documents.csv")
    p.add_argument("--mapping", default="data/events/government_contract_recipient_ticker_map.csv", help="Recipient-name-to-ticker mapping CSV. A starter map is created if missing.")
    p.add_argument("--manifest", nargs="*", default=[], help="Optional source-document manifests for DoD, company press releases, SEC/company docs, or manually collected sources.")
    p.add_argument("--use-usaspending", action="store_true", help="Query USAspending Advanced Award Search for mapped recipients.")
    p.add_argument("--tickers", nargs="*", default=[], help="Limit USAspending recipient searches to mapped public tickers.")
    p.add_argument("--recipient-search", nargs="*", default=[], help="Explicit USAspending recipient search terms.")
    p.add_argument("--start", default="2024-01-01")
    p.add_argument("--end", default="2026-05-23")
    p.add_argument("--limit-per-recipient", type=int, default=3)
    p.add_argument("--pages-per-recipient", type=int, default=1)
    p.add_argument("--min-award-amount", type=float, default=None)
    p.add_argument("--requests-per-second", type=float, default=2.0)
    p.set_defaults(func=cmd.cmd_government_contract_source_docs)

    p = sub.add_parser("parse-government-contracts", help="Parse government-contract source documents into facts, features, and a review queue.")
    p.add_argument("--documents", required=True, help="Government-contract source-document manifest.")
    p.add_argument("--facts-out", required=True)
    p.add_argument("--features-out", required=True)
    p.add_argument("--events-out", required=True)
    p.add_argument("--min-confidence", type=float, default=0.0)
    p.add_argument("--usable-confidence", type=float, default=0.70)
    p.set_defaults(func=cmd.cmd_parse_government_contracts)

    p = sub.add_parser("government-contract-mapping-audit", help="Audit recipient-name-to-ticker mapping coverage for government-contract source rows.")
    p.add_argument("--source-documents", required=True)
    p.add_argument("--mapping", default="data/events/government_contract_recipient_ticker_map.csv")
    p.add_argument("--report-out", required=True)
    p.add_argument("--detail-out", default=None)
    p.set_defaults(func=cmd.cmd_government_contract_mapping_audit)

    p = sub.add_parser("government-contract-gold-template", help="Create a machine-proposed government-contract parser gold-set template requiring human review.")
    p.add_argument("--features", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--target-events", type=int, default=60)
    p.set_defaults(func=cmd.cmd_government_contract_gold_template)

    p = sub.add_parser("government-contract-human-audit", help="Build a reviewed government-contract parser/mapping/funded-vs-ceiling audit sample.")
    p.add_argument("--source-documents", required=True)
    p.add_argument("--features", required=True)
    p.add_argument("--mapping", default="data/events/government_contract_recipient_ticker_map.csv")
    p.add_argument("--events", default=None, help="Optional review/enriched events CSV to annotate with audited review statuses.")
    p.add_argument("--events-out", default=None, help="Optional path for events annotated with audited review statuses.")
    p.add_argument("--audit-out", required=True)
    p.add_argument("--gold-out", required=True)
    p.add_argument("--mapping-errors-out", required=True)
    p.add_argument("--funded-vs-ceiling-errors-out", required=True)
    p.add_argument("--report-out", required=True)
    p.add_argument("--target-events", type=int, default=60)
    p.set_defaults(func=cmd.cmd_government_contract_human_audit)

    p = sub.add_parser("government-contract-public-announcements", help="Create candidates and ingest manifest-driven public-announcement links for government-contract events.")
    p.add_argument("--events", required=True)
    p.add_argument("--manifest", default=None, help="Optional manifest of public-announcement links.")
    p.add_argument("--parser-errors", default=None, help="Reviewed parser audit errors CSV; required for model eligibility.")
    p.add_argument("--candidates-out", required=True)
    p.add_argument("--links-out", required=True)
    p.add_argument("--audit-out", required=True)
    p.add_argument("--eligible-out", required=True)
    p.add_argument("--report-out", required=True)
    p.add_argument("--candidate-limit", type=int, default=300)
    p.add_argument("--target-audit-rows", type=int, default=60)
    p.set_defaults(func=cmd.cmd_government_contract_public_announcements)

    p = sub.add_parser("validate-government-contract-public-links", help="Validate manifest-driven public-announcement links for government-contract events.")
    p.add_argument("--events", required=True)
    p.add_argument("--links", required=True)
    p.add_argument("--parser-errors", default=None, help="Reviewed parser audit errors CSV; required for model eligibility.")
    p.add_argument("--candidates-out", required=True)
    p.add_argument("--links-out", required=True)
    p.add_argument("--audit-out", required=True)
    p.add_argument("--eligible-out", required=True)
    p.add_argument("--report-out", required=True)
    p.add_argument("--candidate-limit", type=int, default=300)
    p.add_argument("--target-audit-rows", type=int, default=60)
    p.set_defaults(func=cmd.cmd_validate_government_contract_public_links)

    p = sub.add_parser("validate-government-contract-parser", help="Validate government-contract parser facts against a reviewed gold-set CSV.")
    p.add_argument("--facts", required=True)
    p.add_argument("--gold", required=True)
    p.add_argument("--errors-out", required=True)
    p.add_argument("--report-out", required=True)
    p.set_defaults(func=cmd.cmd_validate_government_contract_parser)

    p = sub.add_parser("enrich-government-contract-context", help="Add market-cap, revenue-scale, and pre-event run-up context to reviewed government-contract events.")
    p.add_argument("--events", required=True)
    p.add_argument("--prices-dir", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--market-caps", default=None, help="Optional CSV with event_id or ticker/asof_date market_cap_before_event.")
    p.add_argument("--revenue", default=None, help="Optional CSV with event_id or ticker/asof_date revenue_ltm_if_available.")
    p.set_defaults(func=cmd.cmd_enrich_government_contract_context)

    p = sub.add_parser("government-contract-readiness-report", help="Summarize whether a reviewed/enriched government-contract corpus is ready for modeling.")
    p.add_argument("--events", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--source-documents", default=None)
    p.add_argument("--min-train", type=int, default=40)
    p.add_argument("--parser-errors", default=None, help="Optional parser validation errors CSV; if supplied, parser audit must pass.")
    p.set_defaults(func=cmd.cmd_government_contract_readiness_report)

    p = sub.add_parser("activist-13d-source-docs", help="Build Schedule 13D/13G source-document candidates from SEC EDGAR.")
    p.add_argument("--out", required=True)
    p.add_argument("--docs-dir", required=True)
    p.add_argument("--preset")
    p.add_argument("--tickers", nargs="*", default=[])
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--sector-benchmark", default="")
    p.add_argument("--forms", default="SC 13D,SC 13D/A,SC 13G,SC 13G/A")
    p.add_argument("--start", default="2015-01-01")
    p.add_argument("--end", default=None)
    p.add_argument("--limit-per-ticker", type=int, default=None)
    p.add_argument("--user-agent", default=None)
    p.add_argument("--requests-per-second", type=float, default=2.0)
    p.add_argument("--overwrite", action="store_true")
    p.add_argument("--min-text-chars", type=int, default=80)
    p.set_defaults(func=cmd.cmd_activist_13d_source_docs)

    p = sub.add_parser("parse-activist-13d", help="Parse activist/control-intent 13D source documents into facts, features, and a review queue.")
    p.add_argument("--documents", required=True)
    p.add_argument("--facts-out", required=True)
    p.add_argument("--features-out", required=True)
    p.add_argument("--events-out", required=True)
    p.add_argument("--min-confidence", type=float, default=0.0)
    p.add_argument("--usable-confidence", type=float, default=0.60)
    p.set_defaults(func=cmd.cmd_parse_activist_13d)

    p = sub.add_parser("validate-activist-13d-parser", help="Validate activist 13D parser facts against a reviewed gold-set CSV.")
    p.add_argument("--facts", required=True)
    p.add_argument("--gold", required=True)
    p.add_argument("--errors-out", required=True)
    p.add_argument("--report-out", required=True)
    p.set_defaults(func=cmd.cmd_validate_activist_13d_parser)

    p = sub.add_parser("activist-13d-timestamp-audit", help="Audit public timestamps and duplicate filings for activist 13D events.")
    p.add_argument("--events", required=True)
    p.add_argument("--out", required=True)
    p.set_defaults(func=cmd.cmd_activist_13d_timestamp_audit)

    p = sub.add_parser("enrich-activist-13d-context", help="Add market-cap, pre-event run-up, prior-activity, and liquidity context to activist 13D events.")
    p.add_argument("--events", required=True)
    p.add_argument("--prices-dir", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--benchmark", default="SPY")
    p.add_argument("--market-caps", default=None)
    p.add_argument("--prior-activity", default=None)
    p.add_argument("--liquidity", default=None)
    p.set_defaults(func=cmd.cmd_enrich_activist_13d_context)

    p = sub.add_parser("activist-13d-readiness-report", help="Summarize whether a reviewed/enriched activist 13D corpus is ready for modeling.")
    p.add_argument("--events", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--source-documents", default=None)
    p.add_argument("--parser-errors", default=None)
    p.add_argument("--min-train", type=int, default=40)
    p.set_defaults(func=cmd.cmd_activist_13d_readiness_report)
